[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "=1.3.1"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "=0.5.2"

[[constraint]]
  name = "github.com/containernetworking/plugins"
  version = "=0.6.0-rc1"

[[constraint]]
  name = "github.com/docker/docker"
  version = "=1.13.1"

[[constraint]]
  name = "github.com/docker/go-connections"
  version = "=0.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  name = "github.com/robertgzr/go-toml"
  branch = "marshal-map-quoted-key"

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netlink"
